/* warung.h generated by valac 0.20.1, the Vala compiler, do not modify */


#ifndef ____VAPI_WARUNG_H__
#define ____VAPI_WARUNG_H__

#include <glib.h>
#include <webkit/webkit.h>
#include <glib-object.h>
#include <JavaScriptCore/JavaScript.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS


#define WARUNG_TYPE_MAIN (warung_main_get_type ())
#define WARUNG_MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WARUNG_TYPE_MAIN, WarungMain))
#define WARUNG_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WARUNG_TYPE_MAIN, WarungMainClass))
#define WARUNG_IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WARUNG_TYPE_MAIN))
#define WARUNG_IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WARUNG_TYPE_MAIN))
#define WARUNG_MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WARUNG_TYPE_MAIN, WarungMainClass))

typedef struct _WarungMain WarungMain;
typedef struct _WarungMainClass WarungMainClass;
typedef struct _WarungMainPrivate WarungMainPrivate;

#define WARUNG_TYPE_APP (warung_app_get_type ())
#define WARUNG_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WARUNG_TYPE_APP, WarungApp))
#define WARUNG_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WARUNG_TYPE_APP, WarungAppClass))
#define WARUNG_IS_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WARUNG_TYPE_APP))
#define WARUNG_IS_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WARUNG_TYPE_APP))
#define WARUNG_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WARUNG_TYPE_APP, WarungAppClass))

typedef struct _WarungApp WarungApp;
typedef struct _WarungAppClass WarungAppClass;
typedef struct _WarungAppPrivate WarungAppPrivate;

struct _WarungMain {
	WebKitWebView parent_instance;
	WarungMainPrivate * priv;
};

struct _WarungMainClass {
	WebKitWebViewClass parent_class;
};

struct _WarungApp {
	GObject parent_instance;
	WarungAppPrivate * priv;
};

struct _WarungAppClass {
	GObjectClass parent_class;
};


GType warung_main_get_type (void) G_GNUC_CONST;
WarungMain* warung_main_new (void);
WarungMain* warung_main_construct (GType object_type);
void* warung_main_get_context (WarungMain* self);
void warung_main_set_context (WarungMain* self, void* value);
GType warung_app_get_type (void) G_GNUC_CONST;
void* warung_app_repougm (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_repokambing (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_repoarsip (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_update (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_upgrade (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_installapp (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_installbrasero (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_installaudacious (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_installvlc (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_installtotem (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_installfirefox (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_installchromium (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_installpidgin (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_installfilezilla (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_installgeany (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_installgparted (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_installshotwell (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_installstardict (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_installlibreoffice (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_installevolution (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_removebrasero (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_removeaudacious (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_removevlc (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_removetotem (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_removefirefox (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_removechromium (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_removepidgin (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_removefilezilla (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_removegeany (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_removegparted (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_removeshotwell (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_removestardict (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_removelibreoffice (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_removeevolution (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void warung_app_setup_js_class (WarungApp* self, void* context);
WarungApp* warung_app_new (void);
WarungApp* warung_app_construct (GType object_type);
gchar* warung_util_string_from_js_string (void* s);
gchar* warung_util_string_property_from_value (void* ctx, void* val, const gchar* property_name);
void warung_util_evaluate_callback (void* ctx, const gchar* callback, const gchar* args);


G_END_DECLS

#endif
